/**
 * lib/email.js
 *
 * Gmail SMTP email sender using Nodemailer.
 * Sends earnings summaries as formatted HTML emails.
 *
 * Required environment variables:
 *   GMAIL_USER         Your Gmail address (e.g. you@gmail.com)
 *   GMAIL_APP_PASSWORD Your 16-character Gmail App Password
 *   TO_EMAIL           Destination address (can be same as GMAIL_USER)
 */

import nodemailer from "nodemailer";

// ─── Markdown → HTML Converter ─────────────────────────────────────────────
// Lightweight converter — no extra dependency needed.

function markdownToHtml(md) {
  return md
    // H1
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // H2
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    // H3
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    // Bold
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    // Italic
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Inline code
    .replace(/`(.+?)`/g, "<code>$1</code>")
    // Horizontal rule
    .replace(/^---$/gm, "<hr>")
    // Tables — header row
    .replace(/^\|(.+)\|$/gm, (row) => {
      const cells = row
        .split("|")
        .slice(1, -1)
        .map((c) => c.trim());
      // Detect separator row (---|---|---)
      if (cells.every((c) => /^[-:]+$/.test(c))) return "<!-- table-sep -->";
      return (
        "<tr>" +
        cells.map((c) => `<td style="padding:6px 12px;border:1px solid #e2e8f0">${c}</td>`).join("") +
        "</tr>"
      );
    })
    // Wrap table rows in <table>
    .replace(/((<tr>.*<\/tr>\n?)+)/g, (block) => {
      const rows = block.split("\n").filter((r) => r.includes("<tr>"));
      const header = `<tr>${rows[0].match(/<td[^>]*>(.*?)<\/td>/g)?.map((td) => td.replace(/<td/g, "<th style=\"padding:6px 12px;border:1px solid #e2e8f0;background:#f8fafc;font-weight:600\"").replace("</td>", "</th>")).join("") || ""}</tr>`;
      const body = rows.slice(1).join("\n");
      return `<table style="border-collapse:collapse;width:100%;margin:12px 0">${header}${body}</table>`;
    })
    // Remove table sep markers
    .replace(/<!-- table-sep -->\n?/g, "")
    // Unordered list items
    .replace(/^[-*] (.+)$/gm, "<li>$1</li>")
    // Wrap consecutive <li> in <ul>
    .replace(/(<li>.*<\/li>\n?)+/g, (block) => `<ul style="margin:8px 0;padding-left:24px">${block}</ul>`)
    // Numbered list items
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    // Blockquote
    .replace(/^> (.+)$/gm, "<blockquote style=\"border-left:3px solid #94a3b8;margin:8px 0;padding:4px 16px;color:#64748b\">$1</blockquote>")
    // Paragraphs — wrap non-tag lines
    .replace(/^(?!<[a-z/]|$)(.+)$/gm, "<p style=\"margin:8px 0\">$1</p>")
    // Clean up extra whitespace between tags
    .replace(/\n{3,}/g, "\n\n");
}

// ─── Email Template ─────────────────────────────────────────────────────────

function buildEmailHtml(summaryMarkdown, companyName, ticker) {
  const htmlBody = markdownToHtml(summaryMarkdown);
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Earnings Summary: ${companyName} (${ticker})</title>
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif">
  <div style="max-width:720px;margin:32px auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#1e293b 0%,#334155 100%);padding:32px 40px">
      <div style="display:flex;align-items:center;gap:12px">
        <span style="font-size:28px">📊</span>
        <div>
          <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;letter-spacing:-0.3px">
            ${companyName} <span style="color:#94a3b8;font-size:16px;font-weight:500">(${ticker})</span>
          </h1>
          <p style="margin:4px 0 0;color:#94a3b8;font-size:13px">Earnings Call Summary · ${date}</p>
        </div>
      </div>
    </div>

    <!-- Body -->
    <div style="padding:32px 40px;color:#1e293b;font-size:15px;line-height:1.7">
      ${htmlBody}
    </div>

    <!-- Footer -->
    <div style="background:#f8fafc;border-top:1px solid #e2e8f0;padding:20px 40px;text-align:center">
      <p style="margin:0;color:#94a3b8;font-size:12px">
        Generated by your earnings-summarizer · Powered by Claude AI<br>
        Edit <strong>skill.md</strong> to customize the analysis format ·
        Edit <strong>watchlist.json</strong> to add or remove companies
      </p>
    </div>
  </div>
</body>
</html>`;
}

// ─── Send Function ──────────────────────────────────────────────────────────

export async function sendEarningsSummary({ summaryMarkdown, companyName, ticker, quarter }) {
  const gmailUser = process.env.GMAIL_USER;
  const appPassword = process.env.GMAIL_APP_PASSWORD;
  const toEmail = process.env.TO_EMAIL || gmailUser;

  if (!gmailUser || !appPassword) {
    throw new Error(
      "Gmail credentials not set. Add GMAIL_USER and GMAIL_APP_PASSWORD to your environment."
    );
  }

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: gmailUser,
      pass: appPassword, // 16-char App Password (not your Google account password)
    },
  });

  const subject = `📊 ${ticker} ${quarter || "Earnings"} Call Summary`;
  const html = buildEmailHtml(summaryMarkdown, companyName, ticker);

  // Plain-text fallback (strip markdown)
  const text = summaryMarkdown
    .replace(/#{1,6} /g, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`(.+?)`/g, "$1")
    .replace(/^\|.+\|$/gm, "")
    .replace(/^[-*] /gm, "• ")
    .trim();

  const info = await transporter.sendMail({
    from: `"Earnings Summarizer" <${gmailUser}>`,
    to: toEmail,
    subject,
    text,
    html,
  });

  return { messageId: info.messageId, to: toEmail, subject };
}
