/**
 * lib/email.js
 *
 * Sends earnings summaries via Resend (HTTP API — works on Railway free tier).
 *
 * Required environment variables:
 *   RESEND_API_KEY   Get free at https://resend.com (100 emails/day free)
 *   TO_EMAIL         Destination address (where summaries are delivered)
 *
 * Optional:
 *   FROM_EMAIL       Sender address (defaults to onboarding@resend.dev which
 *                    works immediately without domain verification)
 */

import { Resend } from "resend";

// ─── Markdown → HTML ─────────────────────────────────────────────────────────

function markdownToHtml(md) {
  return md
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>")
    .replace(/^---$/gm, "<hr>")
    .replace(/^[-*] (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, b => `<ul style="margin:8px 0;padding-left:24px">${b}</ul>`)
    .replace(/^(?!<[a-z/]|$)(.+)$/gm, "<p style=\"margin:8px 0\">$1</p>")
    .replace(/\n{3,}/g, "\n\n");
}

// ─── Email Template ───────────────────────────────────────────────────────────

function buildHtml(summaryMarkdown, companyName, ticker) {
  const body = markdownToHtml(summaryMarkdown);
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>${companyName} (${ticker}) Earnings</title></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,sans-serif">
  <div style="max-width:700px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)">
    <div style="background:linear-gradient(135deg,#1e293b,#334155);padding:32px 40px">
      <h1 style="margin:0;color:#fff;font-size:22px">
        ${companyName} <span style="color:#94a3b8;font-size:16px">(${ticker})</span>
      </h1>
      <p style="margin:4px 0 0;color:#94a3b8;font-size:13px">Earnings Call Summary · ${date}</p>
    </div>
    <div style="padding:32px 40px;color:#1e293b;font-size:15px;line-height:1.7">${body}</div>
    <div style="background:#f8fafc;border-top:1px solid #e2e8f0;padding:16px 40px;text-align:center">
      <p style="margin:0;color:#94a3b8;font-size:12px">Generated by EarningsIQ · Powered by Claude AI</p>
    </div>
  </div>
</body></html>`;
}

// ─── Send ─────────────────────────────────────────────────────────────────────

export async function sendEarningsSummary({ summaryMarkdown, companyName, ticker, quarter }) {
  const apiKey = process.env.RESEND_API_KEY;
  const toEmail = process.env.TO_EMAIL;

  if (!apiKey) throw new Error("RESEND_API_KEY not set. Get a free key at https://resend.com");
  if (!toEmail) throw new Error("TO_EMAIL not set.");

  const resend = new Resend(apiKey);

  // onboarding@resend.dev works instantly without domain verification.
  // Once you add your own domain in Resend dashboard, set FROM_EMAIL to use it.
  const from = process.env.FROM_EMAIL || "EarningsIQ <onboarding@resend.dev>";

  const { data, error } = await resend.emails.send({
    from,
    to:      [toEmail],
    subject: `📊 ${ticker} ${quarter || "Earnings"} Call Summary`,
    html:    buildHtml(summaryMarkdown, companyName, ticker),
    text:    summaryMarkdown.replace(/#{1,6} /g, "").replace(/\*\*(.+?)\*\*/g, "$1").trim(),
  });

  if (error) throw new Error(error.message);
  return { messageId: data.id, to: toEmail };
}
